# Example api requests

## Media resource

### Get all media
GET http://localhost:3000/api/media

### Get a media item based on id
GET http://localhost:3000/api/media/3?format=plain

### 2nd version
GET http://localhost:3000/api/media/2
### test not found
GET http://localhost:3000/api/media/963

### Modify a media item based on id
PUT http://localhost:3000/api/media/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MzE5NTU0NTMsImV4cCI6MTczMjA0MTg1M30.W3mo4Ps-K2OJRwi0aPpGenQ92o-4-aYJta98W-js4Bw

{
  "title": "Uusi kissakuva",
  "description": "Uutta tietoa kissasta.",
  "user_id": 1,
  "filename": "kissakuva.png",
  "filesize": 123456,
  "media_type": "image/png"
}

### Delete a media item based on id
DELETE http://localhost:3000/api/media/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE3MzE5MjA1MTAsImV4cCI6MTczMjAwNjkxMH0.0Hr7VW0ejp_s0BdWxPksZQWrL4xKTnxgM0YibFzRsaw

### Create an item
POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJwYXNzd29yZCI6InRvLWJlLWhhc2hlZC1wdzEiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJjcmVhdGVkX2F0IjoiMjAyNC0xMS0xM1QxMToxNzoxOC4wMDBaIiwiaWF0IjoxNzMxOTE5ODE4LCJleHAiOjE3MzIwMDYyMTh9.Ys5btjN6XoN5O32EiN7tL2cT4Yq8K-1WiHRdxpkJY9o
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

New cat image
------Boundary
Content-Disposition: form-data; name="description"

Kiva kuva kissasta.
------Boundary
Content-Disposition: form-data; name="user_id"

1
------Boundary
Content-Disposition: form-data; name="file"; filename="kissa2.png"
Content-Type: image/png

< ./media/kissa2.png
------Boundary--







