# User Request

## User resource

### Get all users
GET http://localhost:3000/api/users
Content-Type: application/json

###

### Get a user based on ID
GET http://localhost:3000/api/users/2
Content-Type: application/json

###

### Test not found (invalid user ID)
GET http://localhost:3000/api/users/963
Content-Type: application/json

###

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "karri5",
  "email": "newuser7@example.com",
  "password": "password123"
}

###

### Modify an existing user by ID
PUT http://localhost:3000/api/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNSwidXNlcl9sZXZlbF9pZCI6MSwiaWF0IjoxNzMyNTYzMDU1LCJleHAiOjE3MzI2NDk0NTV9.eIRR0Gelpxr4qhkn7MsEu6lfHZ6lZfbb6Ljh5oBkScs

{
  "username": "hehehehhe",
  "email": "kusetus@gmail.com",
  "user_level_id": "1"
}


### Delete a user by ID
DELETE http://localhost:3000/api/users/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MzIxMDIwMTQsImV4cCI6MTczMjE4ODQxNH0.NIYMBfHv-gHJw_vBFHpQK5IM4Cri3P4mGr1GuOvdunw



## Login resource

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "karri5",
  "password": "password123"
}

### Get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MzI1MjE4NzksImV4cCI6MTczMjYwODI3OX0.iNRvwdEgWeL4D8VWlPFj3NW6rVfkwXUkWJ80tw9vu6w

### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "NewUser",
  "password": "ne",
  "email": "newuser@example.com"
}
